import { computed, markRaw, ref } from "vue";
// Components
import ChInput from "@/components/ui/input/input.vue";
import ChButton from "@/components/ui/button/button.vue";
import ChCheckbox from "@/components/ui/checkbox/checkbox.vue";
import ChFormCategoryTitle from "@/components/pages/NkoInfo/ChFormCategoryTitle.vue";
import { object, bool, lazy } from "yup";
import { rules } from "@/compositions/validation_rules";
markRaw(ChInput);
markRaw(ChButton);
markRaw(ChCheckbox);
//schema validation
export const form = ref({
    inn: "",
    kpp: "",
    ogrn: "",
    fullNameBank: "",
    bik: "",
    countScore: "",
    correspondentScore: "",
    city: "",
    address: "",
    officeOrFlat: "",
    index: "",
    city_actual: "",
    address_actual: "",
    officeOrFlatActual: "",
    index_actual: "",
    city_mailing: "",
    address_mailing: "",
    officeOrFlatMailing: "",
    index_mailing: "",
    actualAddress: true,
    mailingAddress: true,
});

export const validationSchema = computed(() => {
    return object().shape({
        inn: rules.inn,
        kpp: rules.kpp,
        ogrn: rules.ogrn,
        fullNameBank: rules.fullNameBank,
        bik: rules.bik,
        countScore: rules.countScore,
        correspondentScore: rules.correspondentScore,
        city: rules.city,
        city_actual: rules.city_actual,
        city_mailing: rules.city_mailing,
        address: rules.address,
        address_actual: rules.address_actual,
        address_mailing: rules.address_mailing,
        officeOrFlat: rules.officeOrFlat,
        officeOrFlatActual: rules.officeOrFlatActual,
        officeOrFlatMailing: rules.officeOrFlatMailing,
        index: rules.index,
        index_actual: rules.index_actual,
        index_mailing: rules.index_mailing,
        // actualAddress: bool().oneOf([true], ""),
        // mailingAddress: bool().oneOf([true], ""),
    });
});
export const description = validationSchema.value.describe();
export const schema = computed(() => [
    {
        component: ChInput,
        type: "url",
        label: "ИНН *",
        placeholder: "",
        id: "inn",
        model: "inn",
        maxLength: 10,
        apiKey: "inn",
        error: "",
    },
    {
        component: ChInput,
        type: "text",
        label: "КПП *",
        placeholder: "",
        id: "kpp",
        maxLength: 9,
        apiKey: "kpp",
        model: "kpp",
        error: "",
    },
    {
        component: ChInput,
        type: "text",
        label: "ОГРН *",
        placeholder: "",
        id: "ogrn",
        maxLength: 13,
        apiKey: "ogrn",
        model: "ogrn",
        error: "",
    },
    {
        component: ChFormCategoryTitle,
        title: "Банковские реквизиты",
        model: "",
        line: true,
    },
    {
        component: ChInput,
        type: "text",
        label: "Полное наименование банка *",
        placeholder: "",
        id: "fullNameBank",
        apiKey: "full_name",
        model: "fullNameBank",
        error: "",
    },
    {
        component: ChInput,
        type: "url",
        label: "БИК *",
        placeholder: "",
        id: "bik",
        maxLength: 9,
        apiKey: "bik",
        model: "bik",
        error: "",
    },
    {
        component: ChInput,
        type: "url",
        label: "Расчетный счет *",
        placeholder: "",
        id: "countScore",
        maxLength: 20,
        apiKey: "checking_account",
        model: "countScore",
        error: "",
    },
    {
        component: ChInput,
        type: "url",
        label: "Корреспондентский счет *",
        placeholder: "",
        id: "correspondentScore",
        maxLength: 20,
        apiKey: "correspondent_account",
        model: "correspondentScore",
        error: "",
    },
    {
        component: ChFormCategoryTitle,
        title: "Юридический адрес",
        model: "",
        line: true,
    },
    {
        component: ChInput,
        type: "url",
        label: "Город или населенный пункт *",
        placeholder: "",
        id: "city",
        apiKey: "city",
        model: "city",
        error: "",
    },
    {
        component: ChInput,
        type: "url",
        label: "Адрес *",
        placeholder: "",
        id: "address",
        apiKey: "address",
        model: "address",
        error: "",
    },
    [
        {
            component: ChInput,
            type: "url",
            label: "Офис/квартира *",
            placeholder: "",
            id: "officeOrFlat",
            apiKey: "office",
            model: "officeOrFlat",
            error: "",
            style: "margin-right: 8px;",
        },
        {
            component: ChInput,
            type: "url",
            label: "Индекс *",
            placeholder: "",
            id: "index",
            maxLength: 6,
            apiKey: "index",
            model: "index",
            error: "",
        },
    ],
    // acutal address
    {
        component: ChFormCategoryTitle,
        title: "Фактический адрес",
        model: "",
        line: true,
        condition: (model) => !model.mailingAddress,
    },
    {
        component: ChInput,
        type: "url",
        label: "Город или населенный пункт *",
        placeholder: "",
        id: "city_actual",
        apiKey: "city",
        model: "city_actual",
        error: "",
        condition: (model) => !model.mailingAddress,
    },
    {
        component: ChInput,
        type: "url",
        label: "Адрес *",
        placeholder: "",
        id: "address_actual",
        apiKey: "address",
        model: "address_actual",
        error: "",
        condition: (model) => !model.mailingAddress,
    },
    [
        {
            component: ChInput,
            type: "url",
            label: "Офис/квартира *",
            placeholder: "",
            id: "officeOrFlatActual",
            apiKey: "office",
            model: "officeOrFlatActual",
            error: "",
            style: "margin-right: 8px;",
            condition: (model) => !model.mailingAddress,
        },
        {
            component: ChInput,
            type: "url",
            label: "Индекс *",
            placeholder: "",
            id: "index_actual",
            maxLength: 6,
            apiKey: "index",
            model: "index_actual",
            error: "",
            condition: (model) => !model.mailingAddress,
        },
    ],

    //mailing address
    {
        component: ChFormCategoryTitle,
        title: "Почтовый адрес",
        model: "",
        line: true,
        condition: (model) => !model.actualAddress,
    },
    {
        component: ChInput,
        type: "url",
        label: "Город или населенный пункт *",
        placeholder: "",
        id: "city_mailing",
        apiKey: "city",
        model: "city_mailing",
        error: "",
        condition: (model) => !model.actualAddress,
    },
    {
        component: ChInput,
        type: "url",
        label: "Адрес *",
        placeholder: "",
        id: "address_mailing",
        apiKey: "address",
        model: "address_mailing",
        error: "",
        condition: (model) => !model.actualAddress,
    },
    [
        {
            component: ChInput,
            type: "url",
            label: "Офис/квартира *",
            placeholder: "",
            id: "officeOrFlatMailing",
            apiKey: "office",
            model: "officeOrFlatMailing",
            error: "",
            style: "margin-right: 8px;",
            condition: (model) => !model.actualAddress,
        },
        {
            component: ChInput,
            type: "url",
            label: "Индекс *",
            placeholder: "",
            id: "index_mailing",
            maxLength: 6,
            apiKey: "index",
            model: "index_mailing",
            error: "",
            condition: (model) => !model.actualAddress,
        },
    ],
    {
        component: ChCheckbox,
        type: "checkbox",
        label: "Соглашаюсь на обработку",
        id: "actualAddress",
        model: "actualAddress",
        error: "",
        name: "actualAddress",
        slot: `<p>Фактический адрес совпадает с юридическим</p>`,
    },
    {
        component: ChCheckbox,
        type: "checkbox",
        label: "Соглашаюсь на обработку",
        id: "mailingAddress",
        model: "mailingAddress",
        error: "",
        name: "mailingAddress",
        slot: `<p>Почтовый адрес совпадает с юридическим</p>`,
    },
]);

